import type { Metadata } from "next";
import { Poppins } from "next/font/google"; // Import Poppins
import "./globals.css";
import Navbar from "./components/Navbar";
import CartProvider from "./components/Provider";
import ShoppingCartModel from "./components/ShoppingCartModel";

const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700"], // Specify required font weights
  variable: "--font-poppins",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} font-sans antialiased`}>
        <CartProvider>

        <Navbar />
        <ShoppingCartModel/>
        {children}
        </CartProvider>
      </body>
    </html>
  );
}
